### PR TITLE
fix: changed Input.php to be compatible with symfony 6 interface

### PR DESCRIPTION
**Pull request by diego-ninja**
fix: changed Input.php to be compatible with symfony 5 interface

### CODE REVIEW

**Comment by ramsey** [comment]
I'm not sure how to handle this right now. This library supports PHP 7.4 and up, but Symfony 6 packages cannot be installed on PHP 7.4. If I merge these changes, then the Input class will no longer work with Symfony 5.

I can either drop support for PHP 7.4 and all versions of Symfony prior to version 6, or I can choose not to support Symfony 6 yet. 😕

**Comment by mtorromeo** [comment]
I would suggest the following actions:
- release a new major version 2.0 which requires symfony ^6.0 and consequently drops PHP 7.4 support.
- use a separate v1 branch for as long as you want to support PHP 7.4 with only bug fixes
- release 1.3.1 with a bug fix that locks the symfony dependencies to only version 5

the bug fix is necessary to avoid the following fatal error:
```
Fatal error: Declaration of Ramsey\CaptainHook\Input::getFirstArgument() must be compatible with Symfony\Component\Console\Input\InputInterface::getFirstArgument(): ?string in [...]/vendor/ramsey/conventional-commits/src/CaptainHook/Input.php on line 47
```

**Comment by mtorromeo** [comment]
That's right.

I had my situation in mind where "symfony/console" is not present in composer.json at all, and a minor release would fix the problem. I don't know of a better solution...

I still think my proposal would be better than nothing. Some use cases would be fixed, and whoever needs symfony 6 would have an easy fix available by just bumping this package to 2.0.

**Comment by ramsey** [comment]
> I had my situation in mind where "symfony/console" is not present in composer.json at all, and a minor release would fix the problem. 

Composer will still select version 1.3.0, if a dependency of a dependency requires symfony/console version 6, so the bugfix release won't have any effect.

**Comment by ramsey** [comment]
In #48, I've deprecated `Ramsey\CaptainHook\Input`, modified it so that it extends `Symfony\Component\Console\Input\ArrayInput` instead of trying to implement the interface (this avoids any interface differences between Symfony 5 and 6), and I'm no longer actually using it, since I realized this class isn't necessary.

Thank you for contributing! I'm sorry I didn't end up merging this, but what I came up with will allow folks on PHP 7.4 to continue using this, without needing to release a new major version, etc.

**Pull request closed without merging**
