### PR TITLE
chore: allow symfony/console, symfony/filesystem at major version 7

### PR DESCRIPTION
**Pull request by llupa**
## Description

Allow for either Symfony Console, Filesystem 6 or 7.

## Motivation and context

I use this package to have a nice CHANGELOG with conventional commits validated. Right now, it is the only package left so I can bump my last 2 components in Sf 6.4 to Sf 7. 

## How has this been tested?

I ran the test suite locally fully with Sf 7 components installed. They passed 👍 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Maintenance (non-breaking change which adds forward compatibility)

## PR checklist

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING.md** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by alessandro-podo** [comment]
Thank you for creating the pull request. 
I have the same problem as you

I look forward to the pull request ending in a new version soon

**Comment by alepieser** [comment]
Hello @ramsey,

Do you think that there is a chance to accept this pull request soon please ?

With the release of Laravel 11, we are forced to switch to Sf 7 components.

Thanks

**Comment by sojeda** [comment]
Hi, any news about this?

**Comment by ramsey** [comment]
Thank you for contributing! 🎉

**Comment by cgarciagarcia** [comment]
@ramsey it's neccessary a new release tag with these changes. Could you provide a newest? Thanks for your effort!

**Pull request merged**
