### PR TITLE
Add a validate command to CLI to validate commit messages

### PR DESCRIPTION
**Pull request by hussainweb**
## Description
As discussed in https://github.com/ramsey/conventional-commits/issues/57#issuecomment-1191824713, this PR adds a command to validate a commit message

## Motivation and context
More details in #57 and #25.

## How has this been tested?
So far, I have added a few tests and mainly tested this manually. This PR is WIP and I will add more tests.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## PR checklist

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING.md** document.
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Comment by hussainweb** [comment]
I am not sure what to do with the phpstan error in the static analysis stage. FWIW, this breaks on the `main` branch as well. If I find a fix, I'll submit another PR for that.

**Comment by Whax** [comment]
Hello,

I'm really interested with this PR, @hussainweb  any news ? :) 

Thanks

**Comment by hussainweb** [comment]
@ramsey, I have found why there is an error with PHPStan and created #64. Can you please take a look?

**Comment by hussainweb** [comment]
I'm happy to see most relevant checks are passing now. More tests and docs next. I can't do that today though. Maybe tomorrow or later this week.

**Comment by hussainweb** [comment]
Cool. Codecov is happy. I'll work on the docs tomorrow.

**Comment by hussainweb** [comment]
@ramsey, I completed all the tasks and requesting a review now. Thanks!

**Review by ramsey — APPROVED** [review]
Looks great. Thanks! 🎉

**Pull request merged**
